objs <- ls(pos = ".GlobalEnv")
rm(list = objs, pos = ".GlobalEnv")
rm(list = ls())
gc()


source("scripts/app3_ui.R",local=TRUE)
source("scripts/app3_calcSequences.R",local=TRUE)
source("../globalScripts/globalUiFunctions.R",local=TRUE)
source("../globalScripts/sqlLiteQueries.R",local=TRUE)

dependencies<-c("shiny","shinyjs","shinyBS","RSQLite","lubridate","stringr","sf","sp",'shinyFiles')
loadDependencies(dependencies)


ui <- fluidPage(
  tags$head(tags$style("body{ overflow-x:hidden}")),
  tags$style(HTML("
    .row {
      margin-left:0px !important;
      margin-right:0px !important;
  }")),
  HTML("<div id='loadingScreen' style='width:100%; display:none; height:200%; background-color:rgba(0, 0, 0,0.5); color:white; position:absolute; top:0px; left:0px; z-index:5000;'>
  <div id='loadingMessage' style='position:absolute; top:10%; text-align:center; font-size:15px; color:white; width:100%;'></div>
  <img src='spinner.gif' style='position:absolute; top:25%; left:45%;'>
  </div>"),
  useShinyjs(),
  column(12,
  HTML("<div style='width:110% !important; margin-left:-3rem !important; height:10rem !important; padding:4rem !important; background-color:black; color:white; text-align:center !important;'>
    <span style='text-align: center !important; font-size:3rem; width:100% !important; position:absolute !important; top:0px !important; left:0px !important; color:white;>Migration Mapper - Module 3</span>'>
    Migration Mapper 3.1 - App 3
    </div>"),
  actionButton("changeAppsButton", style = "width:15%; font-weight:bolder; position:absolute !important; top:5.5rem !important; left:42.5% !important; border:0px;", "Jump to another Module"),
  # actionButton("loadProjectButton", style = "font-weight:bolder; position:absolute !important; top:5px !important; left:-5px !important;", "Reload Existing Project Folder"),
  shinyDirButton("loadProjectButton", "Reload Existing Project Folder", "Please select a directory",style = "font-weight:bolder; position:absolute !important; top:5px !important; left:-5px !important;"),
  actionButton("closeMappButton", style = "font-weight:bolder; position:absolute !important; top:5px !important; right:5px !important;", "X - CLOSE MAPP")
  ),
  fluidRow(
  column(12,
    p("Using the sequence start and end dates from APP2, MAPP will now export sequence files.
    These files will be used when applying movement models in APP4. There are multiple options here.
    First, sequences can be exported using the exact start and end dates you chose in app2 (left panel).
    Second, you can create custom seasons (right panel)."),
    selectInput('exportShapesSelector', label=NULL,c('Yes, export Shapefiles as well','No, do not export shapefiles'), selected='Yes, export Shapefiles as well')
  ),
  column(6,
    h4('Export Defined Sequences'),
    uiOutput("seasonsIntroText"),
    uiOutput("seasonsDefinedText"),
    hidden(actionButton("calcDefinedSequencesButton", "Export Defined Seasons", style="color: #ffffff; background-color: #15006f; border-color: #000000; padding:1rem;"))
  ),
  column(6,
    h4('Export Custom Seasonal Sequences'),
    p("There are two ways custom seasons can be identified. First, you can identify a new season based on mixtures of start/end dates of previously defined seasons in APP2. For instance, you could develop a season called Winter that starts at the end of MigrationFall and ends at the start of MigrationSpring. Second, and more simply, you can define a season using custom dates that will be used for all ID-YRs."),
    selectInput(
      "typeOfDatesSelector",
      "How would you like to define this season's dates?",
      c(' ','Force season to be between migration dates selected in App 2','Define custom start/end dates for season'),
      multiple = FALSE
    ),
    hidden(
      fluidRow( id="existingSeasonsRow",
      p('enter a name for your new season below'),
      textInput('definedSeasonTextInput', label=NULL, value = "", width = NULL, placeholder = 'enter a season name here'),
      p('Using the two menus below, choose how you want to start and end your custom season. Your newly created season will be pinned between these two dates you selected for each id-yr.'),
      column(6,
        selectInput(
          "startSeasonSelector",
          "Choose start of season",
          c(''),
          multiple = FALSE
        )
      ),
      column(6,
        selectInput(
          "endSeasonSelector",
          "Choose end of season",
          c(''),
          multiple = FALSE
        )
      ),
      p('By default, for individuals where no dates were selected in APP2, sequences will not be generated.
      As an alternative, sequences can be generated by using the average, 5% quantile, or 95% quantile start/end dates from other individuals
      in the population. If you would like to do this, indicate yes below and then choose which method to use for filling in
      missing season start/end dates.'),
      selectInput('shouldAverageSelector', label='create averaged sequences?',c('no do not create sequences','yes create sequences using estimated dates')),
      hidden(
        fluidRow( id="averagingMethodRow",
          column(6,
            p('what method to use for the start sequence'),
            selectInput('averageMethodSelectorOne', label=NULL,c('mean','q95','q05'))
          ),
          column(6,
            p('what method to use for the end sequence'),
            selectInput('averageMethodSelectorTwo', label=NULL,c('mean','q95','q05'))
          )
        )
      ),
      actionButton("calcInBetweenSequencesButton", "Calculate Sequences", style="color: #ffffff; background-color: #15006f; border-color: #000000; padding:1rem;"),
      )
    ),
    hidden(
      fluidRow( id="customSeasonsRow",
      p('enter a name for your new season below'),
      textInput('customSeasonTextInput', label=NULL, value = "", width = NULL, placeholder = 'enter a season name here'),
      p('Choose a start and end date for this season below. The year can be ignored'),
      column(6,
        dateInput("startDateSelector",
            "Choose a start date for this season",
            value = "2022-01-01",
            min = "2022-01-01",
            max = "2022-12-31",
            format="mm-dd"
          )
      ),
      column(6,
        dateInput("endDateSelector",
            "Choose an end date for this season",
            value = "2022-01-01",
            min = "2022-01-01",
            max = "2022-12-31",
            format="mm-dd"
          )
      ),
      actionButton("calcCustomSequencesButton", "Calculate Sequences", style="color: #ffffff; background-color: #15006f; border-color: #000000; padding:1rem;"),
      )
    )
  )
)
)

appThreeReload <- function(filePath){
  loadingScreenToggle('show','loading existing project')
  removeModal()
  rdsLocation<-paste0(filePath,'//workingFile.rds')
  if(file.exists(rdsLocation)){
    workingFile<<-readRDS(rdsLocation)
    importedDatasetMaster<<-workingFile$importedDatasetMaster
    workingFile$masterWorkingDirectory<<-filePath
    masterWorkingDirectory<<-filePath
    dbConnection <<- dbConnect(RSQLite::SQLite(), paste0(masterWorkingDirectory,'//workingDb.db'))
    updateMasterTableFromDatabase()

    getMigtime()
    sessionInfo<-list()
    sessionInfo$masterWorkingDirectory<-masterWorkingDirectory
    sessionInfo$time<-Sys.time()
    saveTo<-paste0(dirname(getwd()),'//session.rds')
    saveRDS(sessionInfo,saveTo)
  }else{
    modalMessager('Error',paste0('Data file from this session does not exist at ',filePath,'. Please try loading the data file manually using the "Reload Existing Project Folder" button.'))
    sessionCheckLocation<-paste0(dirname(getwd()),'//session.rds')
    file.remove(sessionCheckLocation)
  }
  loadingScreenToggle('hide','')
}

getMigtime<-function(){
  dbConnection <<- dbConnect(RSQLite::SQLite(), paste0(masterWorkingDirectory,'//workingDb.db'))
  tables<-dbListTables(dbConnection)
  if('migtime'%in%tables){
    migtime<<-dbGetQuery(dbConnection, "SELECT * FROM migtime")
    migtime$mig1start <<-as.Date(migtime$mig1start)
    migtime$mig1end <<-as.Date(migtime$mig1end)
    migtime$mig2start <<-as.Date(migtime$mig2start)
    migtime$mig2end <<-as.Date(migtime$mig2end)
    migtime$mig3start <<-as.Date(migtime$mig3start)
    migtime$mig3end <<-as.Date(migtime$mig3end)
    migtime$mig4start <<-as.Date(migtime$mig4start)
    migtime$mig4end <<-as.Date(migtime$mig4end)
    migtime$mig5start <<-as.Date(migtime$mig5start)
    migtime$mig5end <<-as.Date(migtime$mig5end)
    migtime$mig6start <<-as.Date(migtime$mig6start)
    migtime$mig6end <<-as.Date(migtime$mig6end)
    migtime$mig7start <<-as.Date(migtime$mig7start)
    migtime$mig7end <<-as.Date(migtime$mig7end)
    migtime$mig8start <<-as.Date(migtime$mig8start)
    migtime$mig8end <<-as.Date(migtime$mig8end)
  }else{

  }
  loadConfig()
}

loadConfig<-function(){
  configOptions<<-readRDS(paste0(masterWorkingDirectory,'//configOptions.rds'))
  configOptions$masterWorkingDirectory<<-masterWorkingDirectory
  calcSeasonAverages()
}



server <- function(input, output, session) {
  checkForSession('app3')
  app3_init(input, output, session)
  onStop(function() {
   stopApp()
 })
}

shiny::devmode(FALSE)
shinyApp(ui, server)
